"""Add data sources and provenance tables

Revision ID: 73af235d17ba
Revises: 'af80e8638e0c'
Create Date: 2026-08-09 00:14:01.541411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73af235d17ba'
down_revision: Union[str, None] = 'af80e8638e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('next_sync', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=True),
    sa.Column('documents_added', sa.Integer(), nullable=True),
    sa.Column('documents_updated', sa.Integer(), nullable=True),
    sa.Column('documents_duplicate', sa.Integer(), nullable=True),
    sa.Column('documents_failed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=True),
    sa.Column('documents_added', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('ingestion_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_errors_id'), 'ingestion_errors', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_errors_run_id'), 'ingestion_errors', ['run_id'], unique=False)
    op.create_table('document_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_domain', sa.String(length=200), nullable=True),
    sa.Column('source_title', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=100), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('original_download_url', sa.String(length=500), nullable=False),
    sa.Column('collection_method', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_provenance_content_hash'), 'document_provenance', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_provenance_document_id'), 'document_provenance', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_provenance_id'), 'document_provenance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_provenance_id'), table_name='document_provenance')
    op.drop_index(op.f('ix_document_provenance_document_id'), table_name='document_provenance')
    op.drop_index(op.f('ix_document_provenance_content_hash'), table_name='document_provenance')
    op.drop_table('document_provenance')
    op.drop_index(op.f('ix_ingestion_errors_run_id'), table_name='ingestion_errors')
    op.drop_index(op.f('ix_ingestion_errors_id'), table_name='ingestion_errors')
    op.drop_table('ingestion_errors')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
