"""Add meeting records and actions tables

Revision ID: af80e8638e0c
Revises: 'b54c3054f0f1'
Create Date: 2026-08-09 00:01:11.164222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af80e8638e0c'
down_revision: Union[str, None] = 'b54c3054f0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_records_id'), 'meeting_records', ['id'], unique=False)
    op.create_table('meeting_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('action_item', sa.Text(), nullable=False),
    sa.Column('responsible_role', sa.String(length=100), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_actions_id'), 'meeting_actions', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_actions_meeting_id'), 'meeting_actions', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_actions_meeting_id'), table_name='meeting_actions')
    op.drop_index(op.f('ix_meeting_actions_id'), table_name='meeting_actions')
    op.drop_table('meeting_actions')
    op.drop_index(op.f('ix_meeting_records_id'), table_name='meeting_records')
    op.drop_table('meeting_records')
    # ### end Alembic commands ###
